import 'package:flutter/material.dart';

// ─── Color Palette ────────────────────────────────────────────────────────────
const Color kGreenPrimary = Color(0xFF2E7D32);
const Color kGreenDark    = Color(0xFF1B5E20);
const Color kGreenLight   = Color(0xFF66BB6A);
const Color kGreenPale    = Color(0xFFE8F5E9);
const Color kGreenAccent  = Color(0xFFA5D6A7);
const Color kGreenMint    = Color(0xFFF1F8E9);
const Color kGreenBorder  = Color(0xFFC8E6C9);

// ─── Equipment Model ──────────────────────────────────────────────────────────
class Equipment {
  final String name;
  final String type;
  final String spec;       // HP / capacity / kit size
  final String price;
  final String priceLabel; // 'Rent' or 'Buy'
  final String owner;
  final String location;
  final double rating;
  final int reviews;
  final bool available;
  final String condition;
  final Color conditionColor;
  final String year;
  final String emoji;

  const Equipment({
    required this.name,
    required this.type,
    required this.spec,
    required this.price,
    required this.priceLabel,
    required this.owner,
    required this.location,
    required this.rating,
    required this.reviews,
    required this.available,
    required this.condition,
    required this.conditionColor,
    required this.year,
    required this.emoji,
  });
}

// ─── Equipment Repository ─────────────────────────────────────────────────────
class EquipmentRepository {
  static const List<Equipment> all = [
    Equipment(
      name: 'John Deere 5310',
      type: 'Tractor',
      spec: '55 HP',
      price: '₹ 1,800/day',
      priceLabel: 'Rent',
      owner: 'Tariq Farms',
      location: 'Lahore',
      rating: 4.8,
      reviews: 34,
      available: true,
      condition: 'Excellent',
      conditionColor: Color(0xFF2E7D32),
      year: '2021',
      emoji: '🚜',
    ),
    Equipment(
      name: 'Mahindra 575 DI',
      type: 'Tractor',
      spec: '47 HP',
      price: '₹ 1,400/day',
      priceLabel: 'Rent',
      owner: 'Ali Brothers',
      location: 'Gujranwala',
      rating: 4.5,
      reviews: 18,
      available: true,
      condition: 'Good',
      conditionColor: Color(0xFF388E3C),
      year: '2019',
      emoji: '🚜',
    ),
    Equipment(
      name: 'New Holland 640',
      type: 'Tractor',
      spec: '75 HP',
      price: '₹ 2,200/day',
      priceLabel: 'Rent',
      owner: 'Chaudhry Estate',
      location: 'Sheikhupura',
      rating: 4.7,
      reviews: 42,
      available: true,
      condition: 'Excellent',
      conditionColor: Color(0xFF2E7D32),
      year: '2022',
      emoji: '🚜',
    ),
    Equipment(
      name: 'Combine Harvester 8010',
      type: 'Harvester',
      spec: '120 HP',
      price: '₹ 3,500/day',
      priceLabel: 'Rent',
      owner: 'Agri Rentals',
      location: 'Sahiwal',
      rating: 4.9,
      reviews: 56,
      available: true,
      condition: 'Excellent',
      conditionColor: Color(0xFF2E7D32),
      year: '2023',
      emoji: '🌾',
    ),
    Equipment(
      name: 'Rice Thresher Pro',
      type: 'Harvester',
      spec: '18 HP',
      price: '₹ 950/day',
      priceLabel: 'Rent',
      owner: 'Punjab Agri Co.',
      location: 'Hafizabad',
      rating: 4.3,
      reviews: 21,
      available: false,
      condition: 'Good',
      conditionColor: Color(0xFF388E3C),
      year: '2020',
      emoji: '🌾',
    ),
    Equipment(
      name: 'Power Sprayer 20L',
      type: 'Sprayer',
      spec: '2 HP Motor',
      price: '₹ 400/day',
      priceLabel: 'Rent',
      owner: 'Seed Center',
      location: 'Faisalabad',
      rating: 4.3,
      reviews: 12,
      available: false,
      condition: 'Good',
      conditionColor: Color(0xFF388E3C),
      year: '2022',
      emoji: '💧',
    ),
    Equipment(
      name: 'Boom Sprayer 400L',
      type: 'Sprayer',
      spec: '12-Nozzle Boom',
      price: '₹ 1,100/day',
      priceLabel: 'Rent',
      owner: 'FarmTech Ltd.',
      location: 'Okara',
      rating: 4.6,
      reviews: 29,
      available: true,
      condition: 'Excellent',
      conditionColor: Color(0xFF2E7D32),
      year: '2023',
      emoji: '💧',
    ),
    Equipment(
      name: 'Drone Sprayer DJI T40',
      type: 'Sprayer',
      spec: '40L Tank',
      price: '₹ 2,800/day',
      priceLabel: 'Rent',
      owner: 'AirAgri',
      location: 'Lahore',
      rating: 4.9,
      reviews: 38,
      available: true,
      condition: 'New',
      conditionColor: Color(0xFF1976D2),
      year: '2024',
      emoji: '🚁',
    ),
    Equipment(
      name: 'Rotavator 7ft',
      type: 'Tool',
      spec: 'PTO Driven',
      price: '₹ 900/day',
      priceLabel: 'Rent',
      owner: 'Farm Tools Co.',
      location: 'Multan',
      rating: 4.1,
      reviews: 9,
      available: true,
      condition: 'Fair',
      conditionColor: Color(0xFFF57C00),
      year: '2018',
      emoji: '⚙️',
    ),
    Equipment(
      name: 'Seed Drill 9-Row',
      type: 'Tool',
      spec: '9-Row, 18cm Gap',
      price: '₹ 750/day',
      priceLabel: 'Rent',
      owner: 'Bajwa Farms',
      location: 'Sargodha',
      rating: 4.4,
      reviews: 15,
      available: true,
      condition: 'Good',
      conditionColor: Color(0xFF388E3C),
      year: '2020',
      emoji: '🌱',
    ),
    Equipment(
      name: 'Disc Plough 3-Bottom',
      type: 'Tool',
      spec: 'Heavy Duty',
      price: '₹ 680/day',
      priceLabel: 'Rent',
      owner: 'Green Field Co.',
      location: 'Jhang',
      rating: 4.0,
      reviews: 7,
      available: true,
      condition: 'Fair',
      conditionColor: Color(0xFFF57C00),
      year: '2017',
      emoji: '⚙️',
    ),
    Equipment(
      name: 'Laser Land Leveler',
      type: 'Tool',
      spec: '±1cm Precision',
      price: '₹ 1,600/day',
      priceLabel: 'Rent',
      owner: 'Precision Agri',
      location: 'Gujrat',
      rating: 4.8,
      reviews: 44,
      available: false,
      condition: 'Excellent',
      conditionColor: Color(0xFF2E7D32),
      year: '2022',
      emoji: '📐',
    ),
    Equipment(
      name: 'Drip Irrigation Kit',
      type: 'Irrigation',
      spec: '1 Acre Complete',
      price: '₹ 85,000',
      priceLabel: 'Buy',
      owner: 'IrriTech',
      location: 'Lahore',
      rating: 4.6,
      reviews: 23,
      available: true,
      condition: 'New',
      conditionColor: Color(0xFF1976D2),
      year: '2026',
      emoji: '🌊',
    ),
    Equipment(
      name: 'Submersible Pump 5HP',
      type: 'Irrigation',
      spec: '5 HP, 4-inch',
      price: '₹ 550/day',
      priceLabel: 'Rent',
      owner: 'Water Tech',
      location: 'Vehari',
      rating: 4.2,
      reviews: 11,
      available: true,
      condition: 'Good',
      conditionColor: Color(0xFF388E3C),
      year: '2021',
      emoji: '💦',
    ),
    Equipment(
      name: 'Solar Water Pump 3HP',
      type: 'Irrigation',
      spec: '3 HP Solar',
      price: '₹ 1,20,000',
      priceLabel: 'Buy',
      owner: 'SolarAgri',
      location: 'Bahawalpur',
      rating: 4.7,
      reviews: 31,
      available: true,
      condition: 'New',
      conditionColor: Color(0xFF1976D2),
      year: '2025',
      emoji: '☀️',
    ),
    Equipment(
      name: 'Sugarcane Harvester',
      type: 'Harvester',
      spec: '100 HP',
      price: '₹ 4,200/day',
      priceLabel: 'Rent',
      owner: 'Sugar Mills Agri',
      location: 'Rahim Yar Khan',
      rating: 4.5,
      reviews: 19,
      available: true,
      condition: 'Good',
      conditionColor: Color(0xFF388E3C),
      year: '2021',
      emoji: '🎋',
    ),
    Equipment(
      name: 'Mini Tiller 7HP',
      type: 'Tractor',
      spec: '7 HP, Walk-behind',
      price: '₹ 380/day',
      priceLabel: 'Rent',
      owner: 'Small Farm Hub',
      location: 'Sialkot',
      rating: 4.3,
      reviews: 8,
      available: true,
      condition: 'Good',
      conditionColor: Color(0xFF388E3C),
      year: '2023',
      emoji: '🔧',
    ),
    Equipment(
      name: 'Potato Digger 2-Row',
      type: 'Tool',
      spec: '2-Row, PTO',
      price: '₹ 820/day',
      priceLabel: 'Rent',
      owner: 'Root Harvest Co.',
      location: 'Okara',
      rating: 4.1,
      reviews: 6,
      available: false,
      condition: 'Fair',
      conditionColor: Color(0xFFF57C00),
      year: '2019',
      emoji: '🥔',
    ),
  ];

  // ─── Filter helpers ──────────────────────────────────────────────────────────
  static List<String> get types =>
      ['All', 'Tractor', 'Sprayer', 'Harvester', 'Tool', 'Irrigation'];

  static List<Equipment> byType(String type) =>
      type == 'All' ? all : all.where((e) => e.type == type).toList();
}